cd D:\ws\blog2019\bigintjson
call checkdep
cd D:\ws\blog2019\build-info\client
call ncu
cd D:\ws\blog2019\build-info\server
call checkdep
cd D:\ws\blog2019\capupload\client
call ncu
cd D:\ws\blog2019\capupload\server
call checkdep
cd D:\ws\blog2019\catch-all-smtp
call checkdep
cd D:\ws\blog2019\cettia\one\client
call ncu
cd D:\ws\blog2019\cettia\one\server
call checkdep
cd D:\ws\blog2019\cettia\simple
call checkdep
cd D:\ws\blog2019\cettia\two\client
call ncu
cd D:\ws\blog2019\cettia\two\server
call checkdep
cd D:\ws\blog2019\credential\client
call ncu
cd D:\ws\blog2019\credential\server
call checkdep
cd D:\ws\blog2019\envers
call checkdep
cd D:\ws\blog2019\fa
call ncu
cd D:\ws\blog2019\googlefont
call ncu
cd D:\ws\blog2019\java11httpclient\client
call checkdep
cd D:\ws\blog2019\java11httpclient\server
call checkdep
cd D:\ws\blog2019\jgit\examples
call checkdep
cd D:\ws\blog2019\jgit\githubbackup
call checkdep
cd D:\ws\blog2019\ky\client
call ncu
cd D:\ws\blog2019\ky\server
call checkdep
cd D:\ws\blog2019\mnistjs\client
call ncu
cd D:\ws\blog2019\mnistjs\train
call ncu
cd D:\ws\blog2019\ratelimit
call checkdep
cd D:\ws\blog2019\sbjooqflyway
call checkdep
cd D:\ws\blog2019\stateless\client
call ncu
cd D:\ws\blog2019\stateless\server
call checkdep
cd D:\ws\blog2019\tfjs-models
call ncu
cd D:\ws\blog2019\tls-and-h2
call checkdep
cd D:\ws\blog2019\totp\client
call ncu
cd D:\ws\blog2019\totp\server
call checkdep
cd D:\ws\blog2019\uploadtus\client
call ncu
cd D:\ws\blog2019\uploadtus\server
call checkdep
cd D:\ws\blog2019\visibility\client
call ncu
cd D:\ws\blog2019\visibility\server
call checkdep
cd D:\ws\blog2019\webocr
call ncu
cd D:\ws\blog2019\webworkers\angular
call ncu
cd D:\ws\blog2019\webworkers\angular-comlink
call ncu
cd D:\ws\blog2019\webworkers\basic
call ncu
cd D:\ws\blog2019\webworkers\earthquakes
call ncu
cd D:\ws\blog2019\webworkers\mandel-with-worker
call ncu
cd D:\ws\blog2019\webworkers\parceljs-comlink
call ncu
pause