/*
 * This file is generated by jOOQ.
 */
package ch.rasc.stateless.db;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ch.rasc.stateless.db.tables.AppSession;
import ch.rasc.stateless.db.tables.AppUser;
import ch.rasc.stateless.db.tables.records.AppSessionRecord;
import ch.rasc.stateless.db.tables.records.AppUserRecord;

/**
 * A class modelling foreign key relationships and constraints of tables in the default
 * schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

  // -------------------------------------------------------------------------
  // UNIQUE and PRIMARY KEY definitions
  // -------------------------------------------------------------------------

  public static final UniqueKey<AppSessionRecord> CONSTRAINT_A = Internal.createUniqueKey(
      AppSession.APP_SESSION, DSL.name("CONSTRAINT_A"),
      new TableField[] { AppSession.APP_SESSION.ID }, true);
  public static final UniqueKey<AppUserRecord> CONSTRAINT_7 = Internal.createUniqueKey(
      AppUser.APP_USER, DSL.name("CONSTRAINT_7"),
      new TableField[] { AppUser.APP_USER.ID }, true);
  public static final UniqueKey<AppUserRecord> CONSTRAINT_76 = Internal.createUniqueKey(
      AppUser.APP_USER, DSL.name("CONSTRAINT_76"),
      new TableField[] { AppUser.APP_USER.EMAIL }, true);

  // -------------------------------------------------------------------------
  // FOREIGN KEY definitions
  // -------------------------------------------------------------------------

  public static final ForeignKey<AppSessionRecord, AppUserRecord> CONSTRAINT_A8 = Internal
      .createForeignKey(AppSession.APP_SESSION, DSL.name("CONSTRAINT_A8"),
          new TableField[] { AppSession.APP_SESSION.APP_USER_ID }, Keys.CONSTRAINT_7,
          new TableField[] { AppUser.APP_USER.ID }, true);
}
