/*
 * This file is generated by jOOQ.
 */
package ch.rasc.ratelimit.db.tables.records;


import ch.rasc.ratelimit.db.tables.Earthquake;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EarthquakeRecord extends UpdatableRecordImpl<EarthquakeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>earthquake.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>earthquake.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>earthquake.time</code>.
     */
    public void setTime(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>earthquake.time</code>.
     */
    public LocalDateTime getTime() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>earthquake.latitude</code>.
     */
    public void setLatitude(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>earthquake.latitude</code>.
     */
    public BigDecimal getLatitude() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>earthquake.longitude</code>.
     */
    public void setLongitude(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>earthquake.longitude</code>.
     */
    public BigDecimal getLongitude() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>earthquake.depth</code>.
     */
    public void setDepth(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>earthquake.depth</code>.
     */
    public BigDecimal getDepth() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>earthquake.mag</code>.
     */
    public void setMag(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>earthquake.mag</code>.
     */
    public BigDecimal getMag() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>earthquake.place</code>.
     */
    public void setPlace(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>earthquake.place</code>.
     */
    public String getPlace() {
        return (String) get(6);
    }

    /**
     * Setter for <code>earthquake.earthquake_id</code>.
     */
    public void setEarthquakeId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>earthquake.earthquake_id</code>.
     */
    public String getEarthquakeId() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EarthquakeRecord
     */
    public EarthquakeRecord() {
        super(Earthquake.EARTHQUAKE);
    }

    /**
     * Create a detached, initialised EarthquakeRecord
     */
    public EarthquakeRecord(Long id, LocalDateTime time, BigDecimal latitude, BigDecimal longitude, BigDecimal depth, BigDecimal mag, String place, String earthquakeId) {
        super(Earthquake.EARTHQUAKE);

        setId(id);
        setTime(time);
        setLatitude(latitude);
        setLongitude(longitude);
        setDepth(depth);
        setMag(mag);
        setPlace(place);
        setEarthquakeId(earthquakeId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised EarthquakeRecord
     */
    public EarthquakeRecord(ch.rasc.ratelimit.db.tables.pojos.Earthquake value) {
        super(Earthquake.EARTHQUAKE);

        if (value != null) {
            setId(value.getId());
            setTime(value.getTime());
            setLatitude(value.getLatitude());
            setLongitude(value.getLongitude());
            setDepth(value.getDepth());
            setMag(value.getMag());
            setPlace(value.getPlace());
            setEarthquakeId(value.getEarthquakeId());
            resetChangedOnNotNull();
        }
    }
}
