/*
 * This file is generated by jOOQ.
 */
package ch.rasc.totp.db;

import javax.annotation.Generated;

import ch.rasc.totp.db.tables.AppUser;

/**
 * Convenience access to all tables in
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.11.11" },
    comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

  /**
   * The table <code>APP_USER</code>.
   */
  public static final AppUser APP_USER = ch.rasc.totp.db.tables.AppUser.APP_USER;
}
