/*
 * This file is generated by jOOQ.
 */
package ch.rasc.ratelimit.db;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ch.rasc.ratelimit.db.tables.Earthquake;

/**
 * This class is generated by jOOQ.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.11.11" },
    comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

  private static final long serialVersionUID = -177109729;

  /**
   * The reference instance of <code></code>
   */
  public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

  /**
   * The table <code>EARTHQUAKE</code>.
   */
  public final Earthquake EARTHQUAKE = ch.rasc.ratelimit.db.tables.Earthquake.EARTHQUAKE;

  /**
   * No further instances allowed
   */
  private DefaultSchema() {
    super("", null);
  }

  /**
   * {@inheritDoc}
   */
  @Override
  public Catalog getCatalog() {
    return DefaultCatalog.DEFAULT_CATALOG;
  }

  @Override
  public final List<Table<?>> getTables() {
    List result = new ArrayList();
    result.addAll(getTables0());
    return result;
  }

  private final List<Table<?>> getTables0() {
    return Arrays.<Table<?>>asList(Earthquake.EARTHQUAKE);
  }
}
