/*
 * This file is generated by jOOQ.
 */
package ch.rasc.ratelimit.db;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import ch.rasc.ratelimit.db.tables.Earthquake;

/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.11.11" },
    comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

  // -------------------------------------------------------------------------
  // INDEX definitions
  // -------------------------------------------------------------------------

  public static final Index PRIMARY_KEY_9 = Indexes0.PRIMARY_KEY_9;

  // -------------------------------------------------------------------------
  // [#1459] distribute members to avoid static initialisers > 64kb
  // -------------------------------------------------------------------------

  private static class Indexes0 {
    public static Index PRIMARY_KEY_9 = Internal.createIndex("PRIMARY_KEY_9",
        Earthquake.EARTHQUAKE, new OrderField[] { Earthquake.EARTHQUAKE.ID }, true);
  }
}
