/*
 * This file is generated by jOOQ.
 */
package ch.rasc.ratelimit.db;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import ch.rasc.ratelimit.db.tables.Earthquake;
import ch.rasc.ratelimit.db.tables.records.EarthquakeRecord;

/**
 * A class modelling foreign key relationships and constraints of tables of the
 * <code></code> schema.
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.11.11" },
    comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

  // -------------------------------------------------------------------------
  // IDENTITY definitions
  // -------------------------------------------------------------------------

  public static final Identity<EarthquakeRecord, Long> IDENTITY_EARTHQUAKE = Identities0.IDENTITY_EARTHQUAKE;

  // -------------------------------------------------------------------------
  // UNIQUE and PRIMARY KEY definitions
  // -------------------------------------------------------------------------

  public static final UniqueKey<EarthquakeRecord> CONSTRAINT_9 = UniqueKeys0.CONSTRAINT_9;

  // -------------------------------------------------------------------------
  // FOREIGN KEY definitions
  // -------------------------------------------------------------------------

  // -------------------------------------------------------------------------
  // [#1459] distribute members to avoid static initialisers > 64kb
  // -------------------------------------------------------------------------

  private static class Identities0 {
    public static Identity<EarthquakeRecord, Long> IDENTITY_EARTHQUAKE = Internal
        .createIdentity(Earthquake.EARTHQUAKE, Earthquake.EARTHQUAKE.ID);
  }

  private static class UniqueKeys0 {
    public static final UniqueKey<EarthquakeRecord> CONSTRAINT_9 = Internal
        .createUniqueKey(Earthquake.EARTHQUAKE, "CONSTRAINT_9", Earthquake.EARTHQUAKE.ID);
  }
}
