/*
 * This file is generated by jOOQ.
 */
package ch.rasc.ratelimit.db;

import ch.rasc.ratelimit.db.tables.Earthquake;

/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

  /**
   * The table <code>EARTHQUAKE</code>.
   */
  public static final Earthquake EARTHQUAKE = Earthquake.EARTHQUAKE;
}
