/*
 * This file is generated by jOOQ.
 */
package ch.rasc.ratelimit.db;

import javax.annotation.Generated;

import ch.rasc.ratelimit.db.tables.Earthquake;

/**
 * Convenience access to all tables in
 */
@Generated(value = { "http://www.jooq.org", "jOOQ version:3.11.11" },
    comments = "This class is generated by jOOQ")
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

  /**
   * The table <code>EARTHQUAKE</code>.
   */
  public static final Earthquake EARTHQUAKE = ch.rasc.ratelimit.db.tables.Earthquake.EARTHQUAKE;
}
