/*
 * This file is generated by jOOQ.
 */
package ch.rasc.ratelimit.db.tables;


import ch.rasc.ratelimit.db.DefaultSchema;
import ch.rasc.ratelimit.db.Keys;
import ch.rasc.ratelimit.db.tables.records.EarthquakeRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Earthquake extends TableImpl<EarthquakeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>earthquake</code>
     */
    public static final Earthquake EARTHQUAKE = new Earthquake();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EarthquakeRecord> getRecordType() {
        return EarthquakeRecord.class;
    }

    /**
     * The column <code>earthquake.id</code>.
     */
    public final TableField<EarthquakeRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>earthquake.time</code>.
     */
    public final TableField<EarthquakeRecord, LocalDateTime> TIME = createField(DSL.name("time"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>earthquake.latitude</code>.
     */
    public final TableField<EarthquakeRecord, BigDecimal> LATITUDE = createField(DSL.name("latitude"), SQLDataType.DECIMAL(10, 7).nullable(false), this, "");

    /**
     * The column <code>earthquake.longitude</code>.
     */
    public final TableField<EarthquakeRecord, BigDecimal> LONGITUDE = createField(DSL.name("longitude"), SQLDataType.DECIMAL(10, 7).nullable(false), this, "");

    /**
     * The column <code>earthquake.depth</code>.
     */
    public final TableField<EarthquakeRecord, BigDecimal> DEPTH = createField(DSL.name("depth"), SQLDataType.DECIMAL(6, 2).nullable(false), this, "");

    /**
     * The column <code>earthquake.mag</code>.
     */
    public final TableField<EarthquakeRecord, BigDecimal> MAG = createField(DSL.name("mag"), SQLDataType.DECIMAL(4, 2).nullable(false), this, "");

    /**
     * The column <code>earthquake.place</code>.
     */
    public final TableField<EarthquakeRecord, String> PLACE = createField(DSL.name("place"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>earthquake.earthquake_id</code>.
     */
    public final TableField<EarthquakeRecord, String> EARTHQUAKE_ID = createField(DSL.name("earthquake_id"), SQLDataType.VARCHAR(18).nullable(false), this, "");

    private Earthquake(Name alias, Table<EarthquakeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Earthquake(Name alias, Table<EarthquakeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>earthquake</code> table reference
     */
    public Earthquake(String alias) {
        this(DSL.name(alias), EARTHQUAKE);
    }

    /**
     * Create an aliased <code>earthquake</code> table reference
     */
    public Earthquake(Name alias) {
        this(alias, EARTHQUAKE);
    }

    /**
     * Create a <code>earthquake</code> table reference
     */
    public Earthquake() {
        this(DSL.name("earthquake"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<EarthquakeRecord, Long> getIdentity() {
        return (Identity<EarthquakeRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<EarthquakeRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_8;
    }

    @Override
    public Earthquake as(String alias) {
        return new Earthquake(DSL.name(alias), this);
    }

    @Override
    public Earthquake as(Name alias) {
        return new Earthquake(alias, this);
    }

    @Override
    public Earthquake as(Table<?> alias) {
        return new Earthquake(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Earthquake rename(String name) {
        return new Earthquake(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Earthquake rename(Name name) {
        return new Earthquake(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Earthquake rename(Table<?> name) {
        return new Earthquake(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Earthquake where(Condition condition) {
        return new Earthquake(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Earthquake where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Earthquake where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Earthquake where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Earthquake where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Earthquake where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Earthquake where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Earthquake where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Earthquake whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Earthquake whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
